insert into Location (Name) values ('Poříčí nad Sázavou');
insert into Location (Name) values ('Cete');
insert into Location (Name) values ('Springfield');
insert into Location (Name) values ('Al Qārah');
insert into Location (Name) values ('Nîmes');
insert into Location (Name) values ('Clearwater');
insert into Location (Name) values ('Arganil');
insert into Location (Name) values ('Shah Alam');
insert into Location (Name) values ('Sugiharjo');
insert into Location (Name) values ('Kallar Kahār');
insert into Location (Name) values ('Mekele');
insert into Location (Name) values ('Kokubu-matsuki');
insert into Location (Name) values ('Dashu');
insert into Location (Name) values ('Kertosari');
insert into Location (Name) values ('Duki');
insert into Location (Name) values ('Orivesi');
insert into Location (Name) values ('Ormstown');
insert into Location (Name) values ('Voiron');
insert into Location (Name) values ('Gamut');
insert into Location (Name) values ('Sutukung');
insert into Location (Name) values ('Nowosielce-Gniewosz');
insert into Location (Name) values ('Al Mushannaf');
insert into Location (Name) values ('Punkalaidun');
insert into Location (Name) values ('Gandusari');
insert into Location (Name) values ('Biaoxi');
insert into Location (Name) values ('Nālūt');
insert into Location (Name) values ('Dingqing');
insert into Location (Name) values ('Irirum');
insert into Location (Name) values ('San Francisco');
insert into Location (Name) values ('Kombësi');
insert into Location (Name) values ('Vsevolozhsk');
insert into Location (Name) values ('Blagoevgrad');
insert into Location (Name) values ('Chosica');
insert into Location (Name) values ('Loznitsa');
insert into Location (Name) values ('Budakovo');
insert into Location (Name) values ('Xinlin');
insert into Location (Name) values ('Carrasqueira');
insert into Location (Name) values ('Costa de Rios Frios');
insert into Location (Name) values ('Lelystad');
insert into Location (Name) values ('Emiliano Zapata');
insert into Location (Name) values ('Mercaderes');
insert into Location (Name) values ('Songjiang');
insert into Location (Name) values ('Huangpi');
insert into Location (Name) values ('Haarlem');
insert into Location (Name) values ('Moravská Nová Ves');
insert into Location (Name) values ('Barisan');
insert into Location (Name) values ('Jambubol');
insert into Location (Name) values ('Jianggezhuang');
insert into Location (Name) values ('Shaxi');
insert into Location (Name) values ('Viñales');
insert into Location (Name) values ('El Peñol');
insert into Location (Name) values ('Seseng');
insert into Location (Name) values ('Baleagung');
insert into Location (Name) values ('Lecong');
insert into Location (Name) values ('Kalahang');
insert into Location (Name) values ('Kurumkan');
insert into Location (Name) values ('Lourdes');
insert into Location (Name) values ('Zhanghuban');
insert into Location (Name) values ('Dasiping');
insert into Location (Name) values ('Dunhou');
insert into Location (Name) values ('Pervomayskiy');
insert into Location (Name) values ('San José Poaquil');
insert into Location (Name) values ('Junqueiro');
insert into Location (Name) values ('Rio Largo');
insert into Location (Name) values ('Mar del Plata');
insert into Location (Name) values ('Aoufous');
insert into Location (Name) values ('San Francisco');
insert into Location (Name) values ('Miřetice');
insert into Location (Name) values ('Timpas');
insert into Location (Name) values ('Santa Ana');
insert into Location (Name) values ('Tamorot');
insert into Location (Name) values ('Paizhou');
insert into Location (Name) values ('Loutrá');
insert into Location (Name) values ('Sarlat-la-Canéda');
insert into Location (Name) values ('Boulogne-Billancourt');
insert into Location (Name) values ('Liren');
insert into Location (Name) values ('Stavropol’');
insert into Location (Name) values ('Batumi');
insert into Location (Name) values ('Upi');
insert into Location (Name) values ('Vatutino');
insert into Location (Name) values ('Hengtanggang');
insert into Location (Name) values ('Phalaborwa');
insert into Location (Name) values ('Cirahab');
insert into Location (Name) values ('Adiwerna');
insert into Location (Name) values ('Bezerros');
insert into Location (Name) values ('Matinao');
insert into Location (Name) values ('Anzihao');
insert into Location (Name) values ('Diên Khánh');
insert into Location (Name) values ('Calubcub Dos');
insert into Location (Name) values ('Wenchang');
insert into Location (Name) values ('Dushang');
insert into Location (Name) values ('Xaçmaz');
insert into Location (Name) values ('Wuyang');
insert into Location (Name) values ('Az Zaytūnīyah');
insert into Location (Name) values ('Karlskrona');
insert into Location (Name) values ('Vilhena');
insert into Location (Name) values ('Ndungu');
insert into Location (Name) values ('Kuidou');
insert into Location (Name) values ('Urcos');
insert into Location (Name) values ('Opatów');
insert into Location (Name) values ('Kiupo');
insert into Location (Name) values ('Giồng Trôm');
insert into Location (Name) values ('Şafāshahr');
insert into Location (Name) values ('Seoam');
insert into Location (Name) values ('Nasielsk');
insert into Location (Name) values ('Pamoyanan');
insert into Location (Name) values ('Stockholm');
insert into Location (Name) values ('Karangora');
insert into Location (Name) values ('Anbyŏn-ŭp');
insert into Location (Name) values ('Kangar');
insert into Location (Name) values ('Sabirabad');
insert into Location (Name) values ('Yinjiang');
insert into Location (Name) values ('Al Lubban al Gharbī');
insert into Location (Name) values ('Zhangjia');
insert into Location (Name) values ('Pershotravneve');
insert into Location (Name) values ('Kofelē');
insert into Location (Name) values ('Valença do Piauí');
insert into Location (Name) values ('Huertas');
insert into Location (Name) values ('Oslo');
insert into Location (Name) values ('Jiangna');
insert into Location (Name) values ('Newark');
insert into Location (Name) values ('Karanlukh');
insert into Location (Name) values ('Santa Cruz do Bispo');
insert into Location (Name) values ('Krasnyy Oktyabr’');
insert into Location (Name) values ('Markópoulo Oropoú');
insert into Location (Name) values ('Fanrong');
insert into Location (Name) values ('Campo Quijano');
insert into Location (Name) values ('Barra de São Francisco');
insert into Location (Name) values ('Tankhoy');
insert into Location (Name) values ('Luhanka');
insert into Location (Name) values ('Betong');
insert into Location (Name) values ('Maksatikha');
insert into Location (Name) values ('Phatthalung');
insert into Location (Name) values ('Loen');
insert into Location (Name) values ('Caaguazú');
insert into Location (Name) values ('Alkmaar');
insert into Location (Name) values ('Semiluki');
insert into Location (Name) values ('Tuochuan');
insert into Location (Name) values ('Mutoko');
insert into Location (Name) values ('Koror');
insert into Location (Name) values ('København');
insert into Location (Name) values ('Pamiers');
insert into Location (Name) values ('Quanshang');
insert into Location (Name) values ('Sangkalputung');
insert into Location (Name) values ('Lidingö');
insert into Location (Name) values ('Tokār');
insert into Location (Name) values ('Noveleta');
insert into Location (Name) values ('Tieba');
insert into Location (Name) values ('Eskilstuna');
insert into Location (Name) values ('Vrangel’');
insert into Location (Name) values ('Mokotów');
insert into Location (Name) values ('Mondorf-les-Bains');
insert into Location (Name) values ('Tosno');
insert into Location (Name) values ('Zhangdiyingzi');
insert into Location (Name) values ('Talodi');
insert into Location (Name) values ('Skrzyszów');
insert into Location (Name) values ('Shuinan');
insert into Location (Name) values ('Yanling');
insert into Location (Name) values ('Nizhnekamsk');
insert into Location (Name) values ('Pereval''noe');
insert into Location (Name) values ('Qalyūb');
insert into Location (Name) values ('Paris La Défense');
insert into Location (Name) values ('Zigong');
insert into Location (Name) values ('Voznesenskaya');
insert into Location (Name) values ('Ordzhonikidze');
insert into Location (Name) values ('Alcantara');
insert into Location (Name) values ('Calimete');
insert into Location (Name) values ('Pasiragung');
insert into Location (Name) values ('Mogotes');
insert into Location (Name) values ('Yuntan');
insert into Location (Name) values ('Lộc Bình');
insert into Location (Name) values ('Lai Cách');
insert into Location (Name) values ('Krajan Pocangan');
insert into Location (Name) values ('Detik Satu');
insert into Location (Name) values ('Krajan');
insert into Location (Name) values ('Santiago Nonualco');
insert into Location (Name) values ('Pajagan');
insert into Location (Name) values ('Dongfeng');
insert into Location (Name) values ('Huangqiao');
insert into Location (Name) values ('Sabinópolis');
insert into Location (Name) values ('Rājshāhi');
insert into Location (Name) values ('Alqueva');
insert into Location (Name) values ('Cienfuegos');
insert into Location (Name) values ('Čapljina');
insert into Location (Name) values ('Mutoko');
insert into Location (Name) values ('Saint-Bruno-de-Guigues');
insert into Location (Name) values ('Buenavista');
insert into Location (Name) values ('Meixi');
insert into Location (Name) values ('Simajia');
insert into Location (Name) values ('Carapelhos');
insert into Location (Name) values ('Sanxi');
insert into Location (Name) values ('Glugur Krajan');
insert into Location (Name) values ('Abeokuta');
insert into Location (Name) values ('Dolní Dunajovice');
insert into Location (Name) values ('Niquinohomo');
insert into Location (Name) values ('Capâo Bonito');
insert into Location (Name) values ('Donghui');
insert into Location (Name) values ('Cañazas');
insert into Location (Name) values ('Yongqin');
insert into Location (Name) values ('Sakharovo');
