insert into Product (Name, Price) values ('Woyzeck', '$238.10');
insert into Product (Name, Price) values ('Mr. Robinson Crusoe', '$869.55');
insert into Product (Name, Price) values ('Red Tent, The (Krasnaya palatka)', '$466.83');
insert into Product (Name, Price) values ('Infidel, The', '$121.57');
insert into Product (Name, Price) values ('Tokio Baby', '$789.29');
insert into Product (Name, Price) values ('Into the Wild', '$932.02');
insert into Product (Name, Price) values ('Rising Sun', '$388.47');
insert into Product (Name, Price) values ('Club, The', '$886.63');
insert into Product (Name, Price) values ('Nayak: The Hero', '$511.53');
insert into Product (Name, Price) values ('Two Sisters from Boston', '$107.83');
insert into Product (Name, Price) values ('Sansa', '$453.79');
insert into Product (Name, Price) values ('Rat Savior, The (Izbavitelj)', '$203.98');
insert into Product (Name, Price) values ('S.O.S. Eisberg', '$593.60');
insert into Product (Name, Price) values ('Brain Smasher... A Love Story (Bouncer and the Lady, The)', '$504.62');
insert into Product (Name, Price) values ('Mega Shark vs. Crocosaurus', '$40.92');
insert into Product (Name, Price) values ('Haaveiden kehä', '$462.27');
insert into Product (Name, Price) values ('Hippie Revolution, The', '$60.62');
insert into Product (Name, Price) values ('Rain or Shine', '$398.32');
insert into Product (Name, Price) values ('Spring Subway', '$343.70');
insert into Product (Name, Price) values ('No Way Home', '$928.48');
insert into Product (Name, Price) values ('Unrest', '$289.89');
insert into Product (Name, Price) values ('Society', '$569.99');
insert into Product (Name, Price) values ('One Nation Under God ', '$832.76');
insert into Product (Name, Price) values ('Pride and Prejudice', '$801.06');
insert into Product (Name, Price) values ('Dirty Dozen, The', '$754.74');
insert into Product (Name, Price) values ('Enforcer, The', '$278.84');
insert into Product (Name, Price) values ('Adventure in Space and Time, An', '$577.78');
insert into Product (Name, Price) values ('Exit Smiling', '$552.92');
insert into Product (Name, Price) values ('Even Cowgirls Get the Blues', '$544.05');
insert into Product (Name, Price) values ('Woman Obsessed', '$377.15');
insert into Product (Name, Price) values ('Kurt Cobain About a Son', '$236.72');
insert into Product (Name, Price) values ('Harry Potter and the Deathly Hallows: Part 2', '$707.98');
insert into Product (Name, Price) values ('Darkness/Light/Darkness (Tma/Svetlo/Tma)', '$144.57');
insert into Product (Name, Price) values ('Vie en Rose, La (Môme, La)', '$517.63');
insert into Product (Name, Price) values ('Life and Nothing But (Vie et rien d''autre, La)', '$214.58');
insert into Product (Name, Price) values ('Jumper', '$913.21');
insert into Product (Name, Price) values ('Eyes Wide Open (Einayim Petukhoth)', '$573.67');
insert into Product (Name, Price) values ('Payment Deferred', '$923.83');
insert into Product (Name, Price) values ('Bluebeard (Barbe-Bleue)', '$408.30');
insert into Product (Name, Price) values ('Taxi', '$201.15');
insert into Product (Name, Price) values ('Carriers', '$775.61');
insert into Product (Name, Price) values ('Merry Widow, The', '$809.34');
insert into Product (Name, Price) values ('Divorcee, The', '$460.28');
insert into Product (Name, Price) values ('Hart of London, The', '$5.70');
insert into Product (Name, Price) values ('Flesh Gordon', '$432.27');
insert into Product (Name, Price) values ('G', '$306.25');
insert into Product (Name, Price) values ('Body Snatcher, The', '$366.70');
insert into Product (Name, Price) values ('Follow Me, Boys!', '$690.12');
insert into Product (Name, Price) values ('Kaena: The Prophecy (Kaena: La prophétie)', '$451.21');
insert into Product (Name, Price) values ('Every Other Weekend (Un week-end sur deux)', '$964.94');
insert into Product (Name, Price) values ('Warren Oates: Across the Border', '$771.01');
insert into Product (Name, Price) values ('William Shakespeare''s Romeo + Juliet', '$804.30');
insert into Product (Name, Price) values ('Night Train', '$592.16');
insert into Product (Name, Price) values ('Stop Train 349', '$690.99');
insert into Product (Name, Price) values ('Ferryman, The', '$379.30');
insert into Product (Name, Price) values ('Choose', '$992.45');
insert into Product (Name, Price) values ('Hugo', '$426.72');
insert into Product (Name, Price) values ('Walled In', '$378.89');
insert into Product (Name, Price) values ('Tango Kabaree', '$429.40');
insert into Product (Name, Price) values ('Cochochi', '$676.27');
insert into Product (Name, Price) values ('Fiancee, The (Parineeta)', '$710.93');
insert into Product (Name, Price) values ('Cape Fear', '$456.00');
insert into Product (Name, Price) values ('Trapped Ashes', '$801.09');
insert into Product (Name, Price) values ('You Were Never Lovelier', '$382.00');
insert into Product (Name, Price) values ('Rigor Mortis (Geung si)', '$537.28');
insert into Product (Name, Price) values ('101 Dalmatians (One Hundred and One Dalmatians)', '$191.86');
insert into Product (Name, Price) values ('Bestseller (Be-seu-teu-sel-leo)', '$585.60');
insert into Product (Name, Price) values ('Black Hand', '$323.66');
insert into Product (Name, Price) values ('Slam Dunk Ernest', '$364.62');
insert into Product (Name, Price) values ('Blood Suckers from Outer Space', '$715.97');
insert into Product (Name, Price) values ('McLibel', '$749.54');
insert into Product (Name, Price) values ('Dudley Do-Right', '$911.85');
insert into Product (Name, Price) values ('Dancer in the Dark', '$429.38');
insert into Product (Name, Price) values ('Massacre Canyon', '$362.17');
insert into Product (Name, Price) values ('Electrick Children', '$349.59');
insert into Product (Name, Price) values ('Tribes', '$467.18');
insert into Product (Name, Price) values ('Freeheld', '$236.65');
insert into Product (Name, Price) values ('Apartment 4E ', '$115.18');
insert into Product (Name, Price) values ('Generation P', '$590.22');
insert into Product (Name, Price) values ('Born to Defense (Zhong hua ying xiong)', '$888.98');
insert into Product (Name, Price) values ('Uptown Saturday Night', '$96.38');
insert into Product (Name, Price) values ('U-571', '$496.34');
insert into Product (Name, Price) values ('Secret Adventures of Gustave Klopp, The (Narco)', '$835.55');
insert into Product (Name, Price) values ('Q', '$966.77');
insert into Product (Name, Price) values ('Johnny Cash at Folsom Prison', '$589.84');
insert into Product (Name, Price) values ('Sea Is Watching, The (Umi wa miteita)', '$948.85');
insert into Product (Name, Price) values ('My Flesh My Blood (Moja krew)', '$462.81');
insert into Product (Name, Price) values ('Huey P. Newton Story, A', '$240.74');
insert into Product (Name, Price) values ('Penelope', '$578.24');
insert into Product (Name, Price) values ('How to Make a Monster', '$413.63');
insert into Product (Name, Price) values ('Battle of the Bulge', '$833.68');
insert into Product (Name, Price) values ('Viva Max!', '$853.43');
insert into Product (Name, Price) values ('Juvenile Court', '$194.78');
insert into Product (Name, Price) values ('Master of the Flying Guillotine (Du bi quan wang da po xue di zi)', '$473.73');
insert into Product (Name, Price) values ('X-Men: Days of Future Past', '$737.26');
insert into Product (Name, Price) values ('Listen to Britain', '$155.62');
insert into Product (Name, Price) values ('Countdown to Looking Glass', '$343.48');
insert into Product (Name, Price) values ('Three Ages', '$234.75');
insert into Product (Name, Price) values ('Make Your Move', '$738.32');
insert into Product (Name, Price) values ('Burn Up!', '$244.69');
insert into Product (Name, Price) values ('Sparkle', '$490.45');
insert into Product (Name, Price) values ('Mask', '$98.42');
insert into Product (Name, Price) values ('Ripley''s Game', '$369.93');
insert into Product (Name, Price) values ('Little Drummer Boy, The', '$9.03');
insert into Product (Name, Price) values ('Those Awful Hats', '$856.99');
insert into Product (Name, Price) values ('Poison Ivy', '$412.38');
insert into Product (Name, Price) values ('Pekka ja Pätkä neekereinä', '$210.00');
insert into Product (Name, Price) values ('Crime at Porta Romana', '$616.53');
insert into Product (Name, Price) values ('Say It Isn''t So', '$874.87');
insert into Product (Name, Price) values ('Onibaba', '$240.42');
insert into Product (Name, Price) values ('Spider', '$344.24');
insert into Product (Name, Price) values ('All the Real Girls', '$91.29');
insert into Product (Name, Price) values ('Escape Plan', '$544.96');
insert into Product (Name, Price) values ('Kiki', '$541.25');
insert into Product (Name, Price) values ('Comedy, The', '$847.00');
insert into Product (Name, Price) values ('True Crime', '$902.24');
insert into Product (Name, Price) values ('Whip Hand, The', '$638.45');
insert into Product (Name, Price) values ('Free Willy', '$326.63');
insert into Product (Name, Price) values ('Melancholia', '$31.84');
insert into Product (Name, Price) values ('Pet Sematary', '$924.02');
insert into Product (Name, Price) values ('Pink Saris', '$119.95');
insert into Product (Name, Price) values ('Welcome to the Rileys', '$912.69');
insert into Product (Name, Price) values ('Bangkok Dangerous', '$621.73');
insert into Product (Name, Price) values ('Collapse', '$588.41');
insert into Product (Name, Price) values ('Secrets of the Tribe', '$372.74');
insert into Product (Name, Price) values ('Lilla Jönssonligan och Cornflakeskuppen', '$134.24');
insert into Product (Name, Price) values ('Lulu in Berlin', '$944.70');
insert into Product (Name, Price) values ('Small Town, The (a.k.a. The Town) (Kasaba)', '$842.47');
insert into Product (Name, Price) values ('Curse of the Werewolf, The', '$565.57');
insert into Product (Name, Price) values ('Taxi Driver', '$392.74');
insert into Product (Name, Price) values ('Cadaver Christmas, A', '$509.98');
insert into Product (Name, Price) values ('Interview with the Vampire: The Vampire Chronicles', '$633.89');
insert into Product (Name, Price) values ('Gorgeous (Boh lee chun)', '$959.56');
insert into Product (Name, Price) values ('School For Scoundrels', '$84.82');
insert into Product (Name, Price) values ('Couch Trip, The', '$884.58');
insert into Product (Name, Price) values ('May', '$842.90');
insert into Product (Name, Price) values ('It''s a Free World...', '$799.52');
insert into Product (Name, Price) values ('Paris Is Burning', '$590.60');
insert into Product (Name, Price) values ('Face of Terror', '$432.56');
insert into Product (Name, Price) values ('Filly Brown', '$105.44');
insert into Product (Name, Price) values ('Easy Virtue', '$564.30');
insert into Product (Name, Price) values ('On the Silver Globe (Na srebrnym globie)', '$977.56');
insert into Product (Name, Price) values ('Miami Vice', '$128.23');
insert into Product (Name, Price) values ('Merchant of Venice, The', '$145.52');
insert into Product (Name, Price) values ('Honeymoon', '$727.65');
insert into Product (Name, Price) values ('Frenchmen 2', '$831.16');
insert into Product (Name, Price) values ('Josephine', '$636.56');
insert into Product (Name, Price) values ('Item, The', '$837.97');
insert into Product (Name, Price) values ('Palestine Is Still the Issue', '$22.65');
insert into Product (Name, Price) values ('King of the Hill', '$678.41');
insert into Product (Name, Price) values ('Far Side of the Moon, The (Face cachée de la lune, La)', '$614.16');
insert into Product (Name, Price) values ('Mob, The', '$538.35');
insert into Product (Name, Price) values ('Violent Men, The', '$962.25');
insert into Product (Name, Price) values ('Good Guys Wear Black', '$572.92');
insert into Product (Name, Price) values ('Earth to Echo', '$347.61');
insert into Product (Name, Price) values ('Loss of Sexual Innocence, The', '$60.89');
insert into Product (Name, Price) values ('Bodies, Rest & Motion', '$765.93');
insert into Product (Name, Price) values ('Origin: Spirits of the Past (Gin-iro no kami no Agito)', '$181.40');
insert into Product (Name, Price) values ('Moonrise', '$87.76');
insert into Product (Name, Price) values ('John Garfield Story, The', '$986.06');
insert into Product (Name, Price) values ('貞子3D', '$639.19');
insert into Product (Name, Price) values ('Agnes Browne', '$398.60');
insert into Product (Name, Price) values ('Snarveien (Detour)', '$715.44');
insert into Product (Name, Price) values ('Since Otar Left (Depuis qu''Otar est parti...)', '$365.97');
insert into Product (Name, Price) values ('Beautiful Joe', '$698.47');
insert into Product (Name, Price) values ('From Dad to Son', '$755.85');
insert into Product (Name, Price) values ('Late August, Early September (Fin août, début septembre)', '$163.35');
insert into Product (Name, Price) values ('Middle of the World, The (O Caminho das Nuvens)', '$917.28');
insert into Product (Name, Price) values ('Buddha Collapsed Out of Shame', '$588.20');
insert into Product (Name, Price) values ('Age of Ignorance, The (a.k.a. Days of Darkness) (L''âge des ténèbres)', '$801.84');
insert into Product (Name, Price) values ('So Undercover', '$947.13');
insert into Product (Name, Price) values ('Last Samurai, The', '$994.71');
insert into Product (Name, Price) values ('Search and Destroy', '$319.81');
insert into Product (Name, Price) values ('Joe Somebody', '$211.39');
insert into Product (Name, Price) values ('General, The', '$556.38');
insert into Product (Name, Price) values ('Navajo Joe', '$252.03');
insert into Product (Name, Price) values ('By the Law', '$433.10');
insert into Product (Name, Price) values ('Facing Ali', '$181.05');
insert into Product (Name, Price) values ('Relative Fear', '$898.08');
insert into Product (Name, Price) values ('Living on One Dollar', '$815.25');
insert into Product (Name, Price) values ('City of Angels', '$184.38');
insert into Product (Name, Price) values ('Dana Carvey: Squatting Monkeys Tell No Lies', '$538.33');
insert into Product (Name, Price) values ('Hansel & Gretel', '$266.32');
insert into Product (Name, Price) values ('36 fillette', '$788.72');
insert into Product (Name, Price) values ('Lynch', '$402.01');
insert into Product (Name, Price) values ('Hello Down There', '$707.77');
insert into Product (Name, Price) values ('Quest', '$787.69');
insert into Product (Name, Price) values ('My Way (Mai Wei)', '$324.76');
insert into Product (Name, Price) values ('Sharktopus', '$503.21');
insert into Product (Name, Price) values ('Magnetic Monster, The', '$496.71');
insert into Product (Name, Price) values ('Boy Meets Girl', '$140.91');
insert into Product (Name, Price) values ('Gallowwalkers', '$672.16');
insert into Product (Name, Price) values ('Island, The', '$856.42');
insert into Product (Name, Price) values ('Godzilla vs. Mechagodzilla II (Gojira VS Mekagojira)', '$244.94');
insert into Product (Name, Price) values ('Barry Munday', '$524.48');
insert into Product (Name, Price) values ('Fun Size', '$852.87');
insert into Product (Name, Price) values ('Grave Decisions (Wer früher stirbt, ist länger tot)', '$309.01');
insert into Product (Name, Price) values ('Free Enterprise', '$638.95');
insert into Product (Name, Price) values ('Ong-Bak: The Thai Warrior (Ong Bak)', '$939.74');
insert into Product (Name, Price) values ('Curse of the Demon (Night of the Demon)', '$129.92');
